services:
  loggingservice:
    build:
      context: .
      dockerfile: LoggingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - loggingdatabase
    networks:
      - app_network
    volumes:
      - app_data:/root/db/
    deploy:
      replicas: 3
  
  loggingdatabase:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - app_data:/root/db/
    command: ["sqlite3", "logs.db"]
    deploy:
      replicas: 2
    networks:
      - app_network
  
  tracingservice:
    build:
      context: .
      dockerfile: TracingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - tracingdatabase
    networks:
      - app_network
    volumes:
      - app_data:/root/db/
    deploy:
      replicas: 3
  
  tracingdatabase:
    image: keinos/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - app_data:/root/db/
    command: ["sqlite3", "traces.db"]
    deploy:
      replicas: 2
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - loggingservice
      - tracingservice
    networks:
      - app_network

volumes:
  app_data:

networks:
  app_network: